spring.application.name=LearningRESTapIs
spring.h2.console.enabled = true
spring.datasource.url=jdbc:h2:file:/Users/amiyasingh/Downloads/LearningRESTapIs/db
spring.datasource.username=amiya
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update